name: test flow
on: push

env:
  CUCUMBER_PUBLISH_TOKEN: 7785c71f-d36d-4075-836e-a6cc988e5256
jobs:
  build:
    name: Run test framework
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: |
          java --version
          mvn clean test
      - name: Publish Test Report
        if: ${{ always() }}
        uses: scacap/action-surefire-report@v1
      - uses: deblockt/cucumber-report-annotations-action@v1.7
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
          path: "**/cucumber-report.json"